name: build script for clean	

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build clean	
        run: make

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: SnakeAndLadders	
          path: ./game
